[[headers]]
for = "/*"
[headers.values]
ACCESS-CONTROL-ALLOW-ORIGIN = "*"
[build]
publish = "apps/calendar/dist"
command = "npm run build:netlify"
[context.production.environment]
NODE_ENV = "production"
[context.acceptance.environment]
NODE_ENV = "production"
[context.deploy-preview.environment]
NODE_ENV = "production"
