[[headers]]
for = "/*"
[headers.values]
ACCESS-CONTROL-ALLOW-ORIGIN = "*"
[build]
  ignore = "git diff --quiet $CACHED_COMMIT_REF $COMMIT_REF -- apps/calendar/ packages/ui/"
publish = "dist"
command = "bun run build:netlify"
[context.production.environment]
NODE_ENV = "production"
[context.acceptance.environment]
NODE_ENV = "production"
[context.deploy-preview.environment]
NODE_ENV = "production"
